In [1]:
import numpy as np

In [2]:
a = np.array([
    [10],
    [20],
    [30],
    [40],
    [50],
    [60]
])
a

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [10]:
np.pad(a, ((0,0),(0,7)), mode="edge")

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50, 50, 50, 50],
       [60, 60, 60, 60, 60, 60, 60, 60]])

In [14]:
b = a.copy()
for i in range (7):
    b = np.hstack((b,a))

In [15]:
b

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50, 50, 50, 50],
       [60, 60, 60, 60, 60, 60, 60, 60]])

In [16]:
b = a.copy()
for i in range (7):
    b = np.concatenate((b,a), axis=1)

In [17]:
b

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50, 50, 50, 50],
       [60, 60, 60, 60, 60, 60, 60, 60]])